# Generated by Django 5.1.3 on 2024-12-18 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_review'),
        ('users', '0002_cart_cartitem_cart_cakes_delete_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cakes',
            field=models.ManyToManyField(through='users.CartItem', to='shops.cake'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shops.cake'),
        ),
    ]
