# Generated by Django 5.1.3 on 2024-12-18 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0002_remove_review_cake_remove_review_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cafe',
        ),
        migrations.DeleteModel(
            name='Cake',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
