# Generated by Django 5.1.3 on 2024-12-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
